language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsqlite3-dev swig2.0 build-essential
  - curl -R -O http://www.lua.org/ftp/lua-5.3.3.tar.gz
  - tar zxf lua-5.3.3.tar.gz
  - cd lua-5.3.3
  - make linux test
  - sudo make install
  - cd ..
  - curl -R -O https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz
  - tar zxf cmake-3.6.2.tar.gz
  - cd cmake-3.6.2
  - ./bootstrap
  - make
  - sudo make install  
  - cd ..
script:
  - cargo build --verbose
  - cargo test --verbose
  - cd ffi/Lua
  - cargo build --verbose
  - cargo test --verbose
