language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsqlite3-dev swig2.0 build-essential liblua5.1-dev lua5.1 libudev-dev
script:
  - cargo build
  - cargo test
  - cd ffi/Lua
  - export LUA_INCLUDE_DIR=/usr/include/lua5.1
  - export LUA_LIBRARY=/usr/lib/x86_64-linux-gnu/liblua5.1.a
  - export LUA_LIBRARIES=/usr/lib/x86_64-linux-gnu/liblua5.1.a
  - cargo build --verbose
  - cargo test
  - cd ../C
  - cargo build
  - cargo test
