# Copyright(C) 2016 Chris Liebert
[package]
name = "quick-3d"
version = "0.1.0"
authors = ["chrisliebert <liebert@pdx.edu>"]

[lib]
name = "quick_3d"
path = "src/lib.rs"

[[bin]]
name = "example"
path = "src/main.rs"

[dependencies]
glium = "*"
nalgebra = "0.8.2"
rusqlite = "0.7.3"
time = "0.1.35"
