# Copyright (C) 2016 Chris Liebert

[package]
name = "quick3dwrapper"
version = "0.1.4"
authors = ["Chris Liebert <liebert@pdx.edu>"]
build = "build.rs"

[build-dependencies]
cmake = "0.1"

[dependencies]

[lib]
name = "quick3dwrappertest"
path = "test.rs"
